# Generated by Django 3.2.25 on 2024-03-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userGetPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photosname', models.CharField(max_length=256, verbose_name='文件名称')),
                ('photostate', models.CharField(max_length=256, verbose_name='处理状态')),
            ],
        ),
        migrations.CreateModel(
            name='userUploadPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photosname', models.CharField(max_length=256, verbose_name='文件名称')),
                ('photostate', models.CharField(max_length=256, verbose_name='处理状态')),
            ],
        ),
    ]
